version: '3.3'
services:
  database:
    image: "apache/couchdb:latest"
    hostname: "localhost"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "test123"
    ports:
      - 5984:5984
    volumes:
      - ./docker:/usr/local/etc/couchdb
